/* ShowUp — health.js (v4.6.132): Apple Health, write-only, iOS app only.
   Classic script, loaded after reminders.js. Runbook 4.7 (App Review 4.2).

   WHAT IT DOES. When you press Finish on a workout, the session you just
   finished is written to Apple Health as workouts:
   - the lifting in it as ONE Traditional Strength Training workout, from your
     first set's time to the moment you pressed Finish (or to your last lifting
     set, if cardio came after it);
   - each cardio entry as its own workout of its own type (running, walking,
     cycling, rowing, swimming, elliptical, stair climbing, jump rope), ending
     when it was logged and lasting the time you logged, with its distance where
     the sport has one.
   Only facts the record attests to. No calories (ShowUp never measures them),
   no heart rate, no invented durations: a row without a timestamp is skipped,
   and so is a session shorter than a minute or longer than six hours.

   WHAT IT NEVER DOES. It never READS Health. The native side requests share
   permission only (read: nil), so iOS never shows a read toggle, and the
   purpose string says so. Nothing leaves the phone: HealthKit is local.

   ONCE PER SESSION. Each workout carries an external id built from its date,
   kind and start time; the ids already sent live on this device, so pressing
   Finish again, reopening the day, or a sync from the web app never writes a
   second copy. Editing a day after it was sent does not rewrite Health.

   THE SWITCH. Off by default, device-local (localStorage), never in synced
   settings -- turning it on on one phone must not raise a permission prompt on
   another. iOS asks when you turn it on. If you decline, it stays off and says
   where to change it. Only in an installed build that carries the native plugin
   (ShowUpHealth, generated by tools/ios-config.py): an older build keeps taking
   web updates and simply shows no Health card. */
const HL_KEY='showup:health', HL_MAX_SENT=400, HL_MIN_MS=60e3, HL_MAX_MS=6*3600e3;
const HL_KIND={Run:'running',Walk:'walking',Cycling:'cycling',Rowing:'rowing',Swimming:'swimming',
  Elliptical:'elliptical','Stair Climber':'stairs','Jump Rope':'jumprope'};
function hlPlugin(){
  try{
    if(!NATIVE_SHELL) return null;
    const cap=window.Capacitor; if(!cap) return null;
    /* a plugin registered from the app's own controller is announced by its
       header; look for it three ways, since the bridge's proxies differ by version */
    const has=!!(cap.isPluginAvailable?.('ShowUpHealth')||(cap.PluginHeaders||[]).some(h=>h&&h.name==='ShowUpHealth')||cap.Plugins?.ShowUpHealth);
    if(!has) return null;
    const P=cap.Plugins?.ShowUpHealth;
    if(P&&typeof P.saveWorkout==='function') return P;
    if(typeof cap.nativePromise==='function')   /* the bridge's own call path, when no proxy was made */
      return {status:o=>cap.nativePromise('ShowUpHealth','status',o||{}),
              requestAuthorization:o=>cap.nativePromise('ShowUpHealth','requestAuthorization',o||{}),
              saveWorkout:o=>cap.nativePromise('ShowUpHealth','saveWorkout',o||{})};
    const R=typeof cap.registerPlugin==='function'?cap.registerPlugin('ShowUpHealth'):null;
    return R&&typeof R.saveWorkout==='function'?R:null;
  }catch(e){ return null; }
}
function hlPrefs(){
  let p={}; try{ p=JSON.parse(localStorage.getItem(HL_KEY)||'{}')||{}; }catch(e){}
  return {on:p.on===true, sent:Array.isArray(p.sent)?p.sent.filter(x=>typeof x==='string'):[]};
}
function hlSetPrefs(p){ try{ localStorage.setItem(HL_KEY,JSON.stringify({on:!!p.on,sent:(p.sent||[]).slice(-HL_MAX_SENT)})); }catch(e){} }
/* the workouts one finished session makes -- pure, for the tests */
function hlWorkouts(iso,rows,endAt){
  const out=[], ok=n=>Number.isFinite(n)&&n>946684800000;
  const cardio=rows.filter(r=>typeof isCardio==='function'&&isCardio(r));
  const lifts=rows.filter(r=>!cardio.includes(r));
  const cardioSpans=[];
  for(const r of cardio){
    const at=Number(r.at), sec=(Number(r.mins)||0)*60+(Number(r.secs)||0);
    if(!ok(at)||!(sec>0)) continue;
    const start=at-sec*1000, kind=HL_KIND[r.ex]||'running';
    cardioSpans.push(start);
    if(at-start<HL_MIN_MS||at-start>HL_MAX_MS) continue;
    const dist=(CARDIO_EX[r.ex]||CARDIO_EX.Run).dist, km=Number(r.w);
    out.push({activity:kind,start,end:at,...(dist&&km>0?{meters:Math.round(km*1000)}:{}),id:`showup-${iso}-${kind}-${start}`});
  }
  const ats=lifts.map(r=>Number(r.at));
  if(lifts.length&&ats.every(ok)){
    const start=Math.min(...ats), last=Math.max(...ats);
    /* lifting ends when you pressed Finish, unless cardio started after the last set */
    const after=cardioSpans.filter(s=>s>=last);
    const end=after.length?last:(ok(endAt)&&endAt>=last?endAt:last);
    if(end-start>=HL_MIN_MS&&end-start<=HL_MAX_MS) out.unshift({activity:'strength',start,end,id:`showup-${iso}-strength-${start}`});
  }
  return out;
}
/* called by stampWorkoutCompletion (js/mascot.js) the moment Finish is pressed */
async function healthOnComplete(record,now){
  const P=hlPlugin(); if(!P) return 'no-shell';
  const pr=hlPrefs(); if(!pr.on) return 'off';
  const iso=todayISO, rows=typeof sessionRows==='function'?sessionRows(record,now):(record.w||[]);
  const want=hlWorkouts(iso,rows,now).filter(w=>!pr.sent.includes(w.id));
  if(!want.length) return 'nothing';
  let saved=0;
  for(const w of want){
    try{ const r=await P.saveWorkout(w); if(r&&r.saved!==false){ saved++; pr.sent.push(w.id); } }catch(e){}
  }
  hlSetPrefs({...hlPrefs(),sent:pr.sent});
  return 'saved:'+saved;
}
/* the switch */
async function healthToggle(on){
  const P=hlPlugin(); if(!P) return 'no-shell';
  if(on){
    let st=null; try{ st=await P.requestAuthorization(); }catch(e){}
    const s=st&&st.status;
    if(s==='unavailable'){ toast('Apple Health is not available on this device.'); return 'unavailable'; }
    if(s!=='authorized'){ hlSetPrefs({...hlPrefs(),on:false}); toast('ShowUp is not allowed to write to Apple Health. In the Health app, tap your picture → Apps → ShowUp.'); return 'denied'; }
  }
  hlSetPrefs({...hlPrefs(),on:!!on});
  toast(on?'Workouts will be saved to Apple Health':'Apple Health off');
  return on?'on':'off';
}
