/* Approved planner journey. Reuses planner.js parsing, checked generation,
   local owner-scoped drafts and saved plan schema. No mock routines or dates. */
const pfLegacy={open:pwOpen,render:pwRender,handle:pwHandle,apply:pwApply,payload:pwPayload,save:pwSave};
function pfOn(){return (pwState?.journey?.prefOrigin==='settings'||planningWorkspace())&&localStorage.getItem('showup:planner-flow')!=='legacy';}
function pfState(){const s=pw();s.journey=s.journey||{page:'dates',furthest:1,anchor:[],removed:[],saved:[]};return s.journey;}
function pfDates(){return [...pw().dates].sort();}
function pfMatch(){return JSON.stringify(pfDates())===JSON.stringify([...pfState().anchor].sort());}
function pfPrefs(){return pwCopy(DB.settings.plannerPreferences||{frequency:5,mode:'time',minutes:45,minSets:20,maxSets:25,emphasis:{},avoid:[],split:'auto'});}
function pfSummary(p=pfPrefs()){const more=Object.keys(p.emphasis).filter(k=>p.emphasis[k]>0);return `${p.frequency==='varies'?'Flexible':p.frequency+' days'} · ${p.mode==='time'?p.minutes+' min':p.minSets+'–'+p.maxSets+' sets'}${more.length?' · More '+more.join(', '):''} · ${p.avoid.length} exercises avoided`;}
function pfShort(d){return new Date(d+'T12:00').toLocaleDateString('en-US',{weekday:'short',month:'numeric',day:'numeric'});}
function pfAnchor(){const j=pfState();if(!pfMatch()){j.furthest=2;j.saved=[];}j.anchor=pfDates();j.furthest=Math.max(j.furthest,2);}
function pfNavigate(page){const s=pw(),j=pfState();if(['days','edit','done'].includes(page)&&!pfMatch())page='dates';j.page=page;s.step='edit';s.datesOpen=false;s.error='';j.clear=false;j.emptyConfirm=false;j.group=null;pwPersist();pwRender();window.scrollTo(0,0);}
function pfStepbar(){const j=pfState(),current={prefs:0,dates:1,days:2,edit:2,done:3}[j.page]??2;return `<div role="navigation" class="pf-steps" aria-label="Planning steps">${['Preferences','Dates','Edit','Done'].map((label,i)=>{const allowed=i<=j.furthest&&(i<2||pfMatch());return pwButton('pf-stage',`<b>${i}</b><span>${label}</span>`,`${i===current?'pf-current':''} ${i<current?'pf-passed':''}`,`data-stage="${i}" ${allowed?'':'disabled'} ${i===current?'aria-current="step"':''}`);}).join('')}</div>`;}
function pfPrefHTML(){const j=pfState(),p=j.prefs||(j.prefs=pfPrefs()),parts=Object.keys(SEED.catalog).filter(x=>x!=='Run');return `<div class="card"><h3>How many days a week?</h3><div class="pf-options">${[1,2,3,4,5,6,7,'varies'].map(n=>pwButton('pf-frequency',n==='varies'?'Varies':n,p.frequency===n?'selected':'',`data-value="${n}" aria-pressed="${p.frequency===n}"`)).join('')}</div><h3>How much per workout?</h3><div class="pw-actions">${['time','sets'].map(m=>pwButton('pf-size',m==='time'?'Time':'Total sets',p.mode===m?'selected':'',`data-value="${m}"`)).join('')}</div><div class="pf-fields">${(p.mode==='time'?[['minutes','Minutes',10,180]]:[['minSets','Minimum sets',1,100],['maxSets','Maximum sets',1,100]]).map(([key,label,min,max])=>`<label>${label}<input type="number" min="${min}" max="${max}" data-pf-pref="${key}" value="${p[key]}"></label>`).join('')}</div></div><div class="card"><h3>Where should we focus?</h3>${parts.map(part=>`<label class="pf-slider"><strong>${hesc(part)}</strong><input type="range" min="-1" max="1" step="1" data-pf-emphasis="${hesc(part)}" value="${p.emphasis[part]||0}" aria-label="${hesc(part)} emphasis" aria-valuetext="${['Less','Balanced','More'][(p.emphasis[part]||0)+1]}"><span><span>Less</span><span>Balanced</span><span>More</span></span></label>`).join('')}<label class="pf-select">Your split<select data-pf-pref="split">${[['auto','Let ShowUp decide'],['full','Full body'],['upper-lower','Upper / Lower · 2-way'],['ppl','Push / Pull / Legs · 3-way'],['body','Body-part split']].map(([v,t])=>`<option value="${v}" ${p.split===v?'selected':''}>${t}</option>`).join('')}</select></label></div><div class="card"><h3>Anything to avoid?</h3><p class="pw-small">Exercises you dislike</p><div class="pw-actions">${p.avoid.map((ex,i)=>pwButton('pf-unavoid',hesc(ex)+' '+icon('clear',ICON_SZ.sm),'',`data-index="${i}" aria-label="Stop avoiding ${hesc(ex)}"`)).join('')}</div><label class="pf-select">Add an exercise<select data-pf-avoid><option value="">Choose exercise</option>${Object.values(SEED.catalog).flat().filter(ex=>!p.avoid.includes(ex)).map(ex=>`<option>${hesc(ex)}</option>`).join('')}</select></label></div>`;}
function pfCalendar(){const s=pw(),j=pfState(),base=new Date((s.month||todayISO.slice(0,7)+'-01')+'T12:00'),first=weekStartDow(),offset=(base.getDay()-first+7)%7,n=new Date(base.getFullYear(),base.getMonth()+1,0).getDate();return `<div class="card"><div class="pw-month">${pwButton('month',icon('chevron',ICON_SZ.sm,180),'pw-icon','data-delta="-1" aria-label="Previous month"')}<strong>${base.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</strong>${pwButton('month',icon('chevron',ICON_SZ.sm),'pw-icon','data-delta="1" aria-label="Next month"')}</div><div class="pw-calendar pf-calendar">${Array.from({length:7},(_,i)=>`<span>${['S','M','T','W','T','F','S'][(first+i)%7]}</span>`).join('')}${'<span></span>'.repeat(offset)}${Array.from({length:n},(_,i)=>{const date=new Date(base);date.setDate(i+1);const d=pwISO(date),selected=s.dates.includes(d),editing=j.anchor.includes(d),saved=!!pwSaved(d)?.items?.length;return pwButton('date',`<span>${i+1}</span><small aria-hidden="true">${saved?'●':'○'}</small>`,`${selected?'selected':''} ${editing?'pf-editing':''}`,`data-date="${d}" aria-pressed="${selected}" aria-label="${hesc(pwDate(d,true))}, ${saved?'plan saved':'no plan'}${editing?', editing draft':''}" ${d<todayISO?'disabled':''}`);}).join('')}</div><div class="pf-calendar-key"><span>● Plan saved</span><span>○ No plan</span><span class="pf-key-selected">Selected</span><span class="pf-key-editing">Editing</span></div><p class="pw-small">${s.dates.length} selected · Up to 7 days</p></div>`;}
function pfRoutine(rows){return pwRowsHTML(rows).replace(/<pre class="pw-prescription">([\s\S]*?)<\/pre>/g,(_,text)=>`<pre class="pw-prescription">${text.split('\n').map(x=>x.trim()).join('\n')}</pre>`);}
function pfDaysHTML(){const s=pw(),j=pfState(),days=pfDates(),all=days.length&&days.every(d=>j.open?.[d]);return `${pfHistoryHTML(true)}<div class="pf-right">${pwButton('pf-expand',icon(all?'collapse':'expand',ICON_SZ.sm)+(all?' Collapse All':' Expand All'),'pw-text')}</div>${days.map(d=>{const b=pwDay(d);return `<section class="pf-day" data-pf-day="${d}"><div class="pf-day-date">${hesc(pfShort(d))}</div><div class="card"><button class="pw-btn pf-day-grip" data-pf-day-grip="${d}" aria-label="Reorder workout for ${hesc(pfShort(d))}; drag or use arrow keys">${icon('grip',ICON_SZ.sm)}</button><details data-pf-fold="${d}" ${j.open?.[d]?'open':''}><summary><strong>${hesc((b.parts.length?b.parts:pwParts(b.rows)).join(' + ')||'Choose body parts')}</strong></summary>${pfRoutine(b.rows)}</details><div class="pw-card-heading"><span class="pw-small">${pwSetCount(b.rows)} sets · ${pwExercises(b.rows).length} exercises</span>${pwAction('pf-edit-day','Edit','edit','pw-text',`data-date="${d}"`)}</div></div></section>`;}).join('')}`;}
function pfGroups(r){const groups=[];for(const [index,line]of(r.lines||[]).entries()){const key=JSON.stringify({...line,reps:undefined,raw:undefined});const g=groups.at(-1);if(g?.key===key){g.indices.push(index);g.line.reps.push(...line.reps);}else groups.push({key,indices:[index],line:{...pwCopy(line)}});}return groups;}
function pfLineText(ex,line){return pwText([{kind:'ex',ex,lines:[line]}]).split('\n').slice(1).map(x=>x.trim()).join('\n');}
function pfEditRows(){const b=pwDay(pw().active);return `<div class="pw-exercises">${b.rows.map((r,i)=>r.kind!=='ex'||!r.ex?`<div data-pw-row="${i}" class="pw-unread"><pre>${hesc(r.raw||'')}</pre>${pwButton('editrow','Edit text','',`data-index="${i}"`)}</div>`:`<article class="pw-exercise pw-editable" data-pw-row="${i}"><button class="pw-btn pw-grip" data-pw-grip="${i}" aria-label="Reorder ${hesc(r.ex)}; drag or use arrow keys">${icon('grip',ICON_SZ.sm)}</button><div class="pw-ex-title"><strong>${hesc(r.ex)}</strong>${pwButton('pf-add-line','+ Add set','pw-text',`data-index="${i}"`)}</div>${pfGroups(r).map((g,k)=>`<div class="pf-set-row"><span class="mono">${hesc(pfLineText(r.ex,g.line))}</span><div>${pwButton('pf-edit-line','Edit','pw-text',`data-index="${i}" data-line="${k}"`)}${pwButton('pf-remove-line','Remove','pw-text',`data-index="${i}" data-line="${k}"`)}</div></div>`).join('')}<div class="pf-right">${pwButton('lock',b.locks.includes(i)?'Kept fixed':'Keep fixed','pw-text',`data-index="${i}" aria-pressed="${b.locks.includes(i)}"`)}</div></article>`).join('')}</div>`;}
function pfHistoryHTML(compact=false){const s=pw(),parts=s.active?(pwDay(s.active).parts.length?pwDay(s.active).parts:pwParts(pwDay(s.active).rows)):[],date=Object.keys(DB.days).filter(d=>d<(s.active||todayISO)&&(DB.days[d].w||[]).length&&(!parts.length||(DB.days[d].w||[]).some(r=>r.part===parts[0]))).sort().at(-1);if(!date)return '';const rows=DB.days[date].w,exercises=[...new Set(rows.map(r=>r.ex))],sets=rows.reduce((n,r)=>n+(r.ex==='Run'?1:(r.reps||[]).length),0);return `<details class="card pf-history" ${compact?'':'open'}><summary><strong>Last workout day</strong><span>${hesc(pfShort(date))}</span></summary><p class="pw-small">${sets} sets · ${exercises.length} exercises · Entire day</p>${exercises.map(ex=>`<div class="pf-history-row"><strong>${hesc(ex)}</strong><p class="mono">${rows.filter(r=>r.ex===ex).map(r=>r.ex==='Run'?hesc(dDisp(r.w)+' '+DU()):hesc(Math.round(toU(r.w))+' '+U()+' × '+(r.reps||[]).join(' ')+(isHold(r.su)?' sec':''))).join('<br>')}</p></div>`).join('')}</details>`;}
function pfDayHTML(){const s=pw(),b=pwDay(s.active),j=pfState(),total=pwSetCount(b.rows),changed=b.target!=null&&b.target!==total;return `<div class="pw-datebar">${pwTabs()}${pwDatesButton('pf-dates')}</div><details class="pw-setup"><summary><strong>${hesc((b.parts.length?b.parts:pwParts(b.rows)).join(' + ')||'Select body parts')}</strong></summary><div class="pw-parts">${Object.keys(SEED.catalog).map(p=>pwButton('part',hesc(p),b.parts.includes(p)?'selected':'',`data-date="${s.active}" data-part="${hesc(p)}"`)).join('')}</div></details><div class="pw-actions">${pwAction('pf-regenerate','Regenerate','sparkle',changed?'primary pf-beam':'')}${pwAction('paste','Paste','paste')}${pwAction('pf-clear','Clear','clear','pw-text')}</div><div class="pf-total"><span>Total sets</span><div class="pw-stepper">${pwButton('pf-minus','−','','aria-label="Decrease total sets"'+(!b.rows.length?' disabled':''))}<output class="${changed?'pf-changed':''}">${b.target??total}</output>${pwButton('pf-plus','+','','aria-label="Increase total sets"'+(!b.rows.length?' disabled':''))}</div></div>${changed?'<p class="pf-balloon" role="status">Hit Regenerate to factor in the changed Total sets amount</p>':''}${j.group?pfGroupForm():''}<div class="card">${b.rows.length?pfEditRows():'<p>No exercises yet.</p>'}</div><div class="pf-add-summary">${pwButton('add','+ Add exercise','pf-add-button')}<p class="pw-small">${hesc(pfShort(s.active))} · ${total} sets · ${pwExercises(b.rows).length} exercises</p></div>${b.undo?pwButton('undo','Undo','pw-text'):''}${pfHistoryHTML()}`;}
function pfGroupForm(){const g=pfState().group;return `<div class="card pf-group-form"><h3>${g.add?'Add set':'Edit sets'}</h3><div class="pf-fields"><label>Weight (${hesc(g.line.unit||U())})<input id="pf-weight" type="number" min="0" step="any" value="${g.line.w||0}"></label><label>${isHold(g.line.su)?'Seconds per set':'Reps per set'}<input id="pf-reps" value="${g.line.reps.join(' ')}" aria-describedby="pf-reps-help"></label></div><p id="pf-reps-help" class="pw-small">Separate each set with a space.</p><div class="pw-actions">${pwButton('pf-group-save','Keep changes','primary')}${pwButton('pf-group-cancel','Cancel')}</div></div>`;}
function pfPending(){return pw().dates.some(d=>{const b=pwDay(d);return b.target!=null&&b.target!==pwSetCount(b.rows);});}
function pfValidateCandidate(candidate,dates){
 const p=pfPrefs(),expected=[...dates].sort(),received=Object.keys(candidate.days).sort();
 if(JSON.stringify(expected)!==JSON.stringify(received))throw Error('The writer returned different dates. Your draft is unchanged.');
 for(const [date,day] of Object.entries(candidate.days)){
  const avoided=day.rows.filter(r=>p.avoid.some(ex=>ex.trim().toLowerCase()===String(r.ex||'').trim().toLowerCase()));
  if(avoided.length)throw Error('The writer included an avoided exercise: '+avoided.map(r=>r.ex).join(', ')+'. Your draft is unchanged.');
  const total=pwSetCount(day.rows);
  if(!total)throw Error(pfShort(date)+' has no planned sets. Your draft is unchanged.');
  if(candidate.type!=='adjust'&&p.mode==='sets'&&(total<p.minSets||total>p.maxSets))throw Error(pfShort(date)+' is outside your '+p.minSets+'–'+p.maxSets+' set range. Your draft is unchanged.');
 }
}
function pfSaveButton(){return pwButton('pf-save',pw().dates.length?`Save ${pw().dates.length} ${pw().dates.length===1?'day':'days'}`:'Save changes','primary',(!pw().dates.length&&!pfState().removed.length)||pfPending()?'disabled':'');}
function pfRender(){const s=pw(),j=pfState(),panel=['paste','editrow','adjust','candidate','busy'].includes(s.step);if(panel){pfLegacy.render();const box=document.querySelector('.pw-workspace');if(box){box.classList.add('pf-workspace');box.insertAdjacentHTML('afterbegin',pfStepbar());if(s.step==='paste'&&!s.editAll)box.querySelector('.pw-input-panel')?.insertAdjacentHTML('beforeend',`<label class="pw-small"><input type="checkbox" data-pf-paste-all ${j.pasteAll?'checked':''}> Use this routine for all selected days</label>`);}return;}let body='',footer='',heading={dates:'Choose your dates',prefs:'Your preferences',days:'Edit your plan',edit:'Edit your routine',done:'Your dates are updated'}[j.page];
 if(j.page==='prefs'){body=pfPrefHTML();footer=pwButton('pf-prefs-save','Save preferences','primary');}
 else if(j.page==='dates'){body=`<div class="card"><div class="pw-card-heading"><strong>Your preferences</strong>${pwAction('pf-prefs','Edit','edit','pw-text')}</div><p class="pw-small">${hesc(pfSummary())}</p></div>${pfCalendar()}<p class="pw-small">Generating creates a draft. Saving replaces existing plans only on the selected dates. Logged workouts stay untouched.</p>`;footer=pwAction('pf-generate','Generate plan','sparkle','primary',s.dates.length?'':'disabled')+pwAction('pf-paste-dates','Paste','paste','',s.dates.length?'':'disabled');}
 else if(j.page==='days'){body=pfDaysHTML();footer=pwButton('pf-edit-first','Edit first day →','primary',s.dates.length?'':'disabled')+pfSaveButton()+'<p class="pw-small">Saves every routine above to its date.</p>';}
 else if(j.page==='edit'&&s.active){body=pfDayHTML();const ds=pfDates(),i=ds.indexOf(s.active),prev=ds[i-1],next=ds[i+1],short=d=>new Date(d+'T12:00').toLocaleDateString('en-US',{month:'numeric',day:'numeric'});footer=`<div class="pf-neighbors">${pwButton('pf-edit-day',prev?'← Edit '+short(prev):'Previous day','',prev?`data-date="${prev}"`:'disabled')}${pwButton('pf-edit-day',next?'Edit '+short(next)+' →':'Next day','',next?`data-date="${next}"`:'disabled')}</div>`+pfSaveButton();}
 else if(j.page==='done'){body=`<div class="card">${(j.saved||[]).map(x=>`<div class="pf-saved"><strong>${hesc(pfShort(x.date))}</strong><p class="pw-small">${x.sets?`${hesc(x.parts.join(' + '))} · ${x.sets} sets`:'No plan'}</p></div>`).join('')}</div><p class="pw-small">Further edits are saved only when you tap Save again.</p>`;footer=pwButton('close','Back to Today','primary');}
 if(j.clear){body=`<div class="card" role="alert"><h3>Clear ${hesc(pfShort(s.active))}?</h3>${pwButton('pf-remove-day','Remove this day')}<p class="pw-small">Remove its plan when you save.</p>${pwButton('pf-empty-day','Keep day, empty routine')}<p class="pw-small">Add exercises manually. No logged workouts change.</p>${pwButton('pf-clear-cancel','Cancel')}</div>`;footer='';}
 if(j.emptyConfirm){const empty=pfDates().filter(d=>!pwSetCount(pwDay(d).rows)),valid=s.dates.length-empty.length;body=`<div class="card" role="alert"><h3>Empty days won’t be saved</h3>${empty.map(d=>`<p><strong>${hesc(pwDate(d))}</strong><br>0 planned sets · No plan</p>`).join('')}<p class="pw-small">These dates will become No plan. Any existing saved plan on these dates will be removed. Logged workouts stay untouched.</p>${pwButton('pf-confirm-save',valid?'Save '+valid+' days & clear empty days':'Set dates to No plan','primary')}${pwButton('pf-clear-cancel','Back to editing')}</div>`;footer='';}
 if(s.conflict){body=`<div class="card" role="alert"><h3>Newer plan · ${hesc(pwDate(s.conflict))}</h3>${pfRoutine(pwRead(planText(pwSaved(s.conflict))))}${pwButton('load-newer','Use newer plan')}${pwButton('replace-newer','Keep my draft')}</div>`;footer='';}
 $('#view').innerHTML=pwFoldMarkup(`<section class="pw-workspace pf-workspace" aria-label="Planning workspace">${j.prefOrigin==='settings'&&j.page==='prefs'?'':pfStepbar()}<div class="pw-editor-head"><button class="icobtn" data-pw="pf-back" aria-label="Back">←</button><h1>${heading||'Edit your plan'}</h1></div>${s.error?`<p class="pw-message" role="alert">${hesc(s.error)}</p>`:''}${body}<span id="pw-reorder-help" class="pw-sr-only">Drag or use arrow keys to reorder.</span><span id="pw-reorder-status" role="status" class="pw-sr-only"></span>${footer?`<div class="pw-save-dock pf-dock">${footer}</div>`:''}</section>`);requestAnimationFrame(pwPositionDock);
}
pwRender=function(){return pfOn()?pfRender():pfLegacy.render();};
pwOpen=function(d,step){if(!pfOn())return pfLegacy.open(d,step);const s=pw(),j=pfState();if(s.busy){pwRequest++;lift.writeAbort?.abort();s.busy=false;}if(d){s.dates=[d];s.active=d;s.month=d.slice(0,7)+'-01';pwDay(d);}else if(!s.dates.length){s.active=dayClosed()?tomorrowISO():writeDateISO();s.dates=[s.active];pwDay(s.active);}j.page=step==='dates'?'dates':d&&pwSaved(d)?'days':d?'dates':j.page;j.prefOrigin=null;if(d&&pwSaved(d))pfAnchor();lift.plan='workspace';view='today';s.step='edit';pwPersist();render({soft:true});};
pwApply=function(add=false){if(!pfOn())return pfLegacy.apply(add);const c=pw().candidate;if(!c)return;const generated=c.type==='generate',adjust=c.type==='adjust';if(c.type==='paste'&&c.index===undefined&&pfState().pasteAll){const one=Object.values(c.days)[0];c.days=Object.fromEntries(pfDates().map(d=>[d,pwCopy(one)]));}pfLegacy.apply(add);for(const d of Object.keys(c.days)){pwDay(d).target=null;}pfAnchor();pfNavigate(generated?'days':'edit');};
pwPayload=function(dates,action){const p=pfLegacy.payload(dates,action);if(!pfOn())return p;const prefs=pfPrefs();p.workspace.preferences=prefs;p.note=[p.note,'Confirmed planning preferences: '+JSON.stringify(prefs),"Respect avoided exercises. Frequency describes the usual week; only generate the explicitly selected dates. Time is an approximate budget, not a promise."].filter(Boolean).join('\n');return p;};
function pfMoveDay(from,to){const ds=pfDates(),a=ds.indexOf(from),b=ds.indexOf(to);if(a<0||b<0||a===b)return;const bundles=ds.map(d=>pwCopy(pwDay(d))),[moved]=bundles.splice(a,1);bundles.splice(b,0,moved);ds.forEach((d,i)=>{const old=pwDay(d);pw().book[d]={...bundles[i],base:old.base,source:'Your draft'};});pwPersist();pwRender();}
function pfSave(confirm=false){const s=pw(),j=pfState();if(!pfMatch())throw Error('Restore the editing dates, or generate a new draft first.');if(pfPending())throw Error('Regenerate the changed total sets before saving.');const empty=s.dates.filter(d=>!pwSetCount(pwDay(d).rows));if(empty.length&&!confirm){j.emptyConfirm=true;pwRender();return;}
 const dates=[...new Set([...s.dates,...j.removed.map(x=>x.date)])];if(!dates.length)throw Error('Choose at least one date.');
 for(const d of dates){if(d<todayISO)throw Error('A draft date has passed. Choose today or a future date.');const base=j.removed.find(x=>x.date===d)?.base??pwDay(d).base;if(base!==pwFingerprint(d)){s.conflict=d;throw Error(`${pwDate(d)} changed on another device. Review it before saving.`);}}
 const days=pwCopy(DB.week?.days||{}),at=Date.now();j.saved=dates.map(d=>({date:d,sets:j.removed.some(x=>x.date===d)?0:pwSetCount(pwDay(d).rows),parts:pwParts(pwDay(d).rows)}));
 for(const d of dates){const remove=empty.includes(d)||j.removed.some(x=>x.date===d);if(remove){delete days[d];if(DB.plan?.d===d){DB.plan=null;DB.planAt=at;}}else{const b=pwDay(d),doc={...planItemsFrom(b.rows),raw:pwText(b.rows),title:pwParts(b.rows).join(' + ')};days[d]=doc;if(DB.plan?.d===d){DB.plan={d,...doc};DB.planAt=at;}}}
 const all=Object.keys(days).sort();DB.week=all.length?{from:all[0],to:all.at(-1),days,raw:'',at}:null;DB.weekAt=at;planRailRefresh();save(true);for(const d of s.dates){const b=pwDay(d);b.base=pwFingerprint(d);b.source='Saved plan';delete b.undo;}j.removed=[];j.furthest=3;j.emptyConfirm=false;pfNavigate('done');
}
pwSave=function(){return pfOn()?pfSave():pfLegacy.save();};
function pfHandle(a,el){const s=pw(),j=pfState(),d=el.dataset.date,i=+el.dataset.index,b=s.active?pwDay(s.active):null;
 if(a==='pf-settings'){j.prefOrigin='settings';j.prefs=pfPrefs();lift.plan='workspace';view='today';pfNavigate('prefs');return;}
 if(a==='pf-prefs'){j.prefOrigin=j.page;j.prefs=pfPrefs();pfNavigate('prefs');return;}
 if(a==='pf-back'){if(j.page==='prefs'){if(j.prefOrigin==='settings'){j.prefOrigin=null;lift.plan=null;view='sync';render();}else pfNavigate(j.prefOrigin||'dates');}else if(j.page==='edit')pfNavigate('days');else if(j.page==='days'||j.page==='done')pfNavigate('dates');else{lift.plan=null;view='today';render();}return;}
 if(a==='pf-stage'){j.prefOrigin=null;const n=+el.dataset.stage;if(n>j.furthest||n>=2&&!pfMatch())return;pfNavigate(['prefs','dates','days','done'][n]);return;}
 if(a==='pf-frequency'){j.prefs.frequency=el.dataset.value==='varies'?'varies':+el.dataset.value;}
 else if(a==='pf-size')j.prefs.mode=el.dataset.value;
 else if(a==='pf-unavoid')j.prefs.avoid.splice(i,1);
 else if(a==='pf-prefs-save'){const p=j.prefs;if(!p||!Number.isInteger(p.minutes)||p.minutes<10||p.minutes>180||!Number.isInteger(p.minSets)||!Number.isInteger(p.maxSets)||p.minSets<1||p.maxSets>100||p.minSets>p.maxSets)throw Error('Use valid whole numbers. Minimum sets cannot exceed maximum.');DB.settings.plannerPreferences=pwCopy(p);DB.settingsAt=Date.now();save(true);if(j.prefOrigin==='settings'){j.prefOrigin=null;lift.plan=null;view='sync';render();return;}pfNavigate(j.prefOrigin||'dates');return;}
 else if(a==='pf-dates'){pfNavigate('dates');return;}
 else if(a==='pf-generate'){if(!s.dates.length)return;j.anchorBefore=pwCopy(j.anchor);pwGenerate();return;}
 else if(a==='pf-paste-dates'){if(!s.dates.length)return;s.active=s.dates[0];s.editIndex=undefined;s.pasteText='';s.step='paste';}
 else if(a==='pf-expand'){j.open=j.open||{};const open=!s.dates.every(x=>j.open[x]);s.dates.forEach(x=>j.open[x]=open);}
 else if(a==='pf-edit-day'||a==='pf-edit-first'){s.active=d||pfDates()[0];pfNavigate('edit');return;}
 else if(a==='pf-clear'){j.clear=true;}
 else if(a==='pf-clear-cancel'){j.clear=false;j.emptyConfirm=false;}
 else if(a==='pf-empty-day'){pwUndoPoint(b);b.rows=[];b.parts=[];b.locks=[];b.target=null;b.cleared=true;b.source='Your draft';j.clear=false;}
 else if(a==='pf-remove-day'){j.removed.push({date:s.active,base:b.base});s.dates=s.dates.filter(x=>x!==s.active);j.anchor=j.anchor.filter(x=>x!==s.active);s.active=s.dates[0]||null;pfNavigate('days');return;}
 else if(a==='pf-plus'||a==='pf-minus'){const total=pwSetCount(b.rows),limit=pwSetLimits(b);b.target=Math.max(limit.min,Math.min(limit.max,(b.target??total)+(a==='pf-plus'?1:-1)));if(b.target===total)b.target=null;}
 else if(a==='pf-regenerate'){pwGenerate(b.target!=null&&b.target!==pwSetCount(b.rows),true);return;}
 else if(a==='pf-edit-line'||a==='pf-add-line'){const r=b.rows[i],g=a==='pf-add-line'?null:pfGroups(r)[+el.dataset.line];j.group={index:i,indices:g?.indices||[],line:pwCopy(g?.line||r.lines.at(-1)||{w:0,unit:U(),reps:[8]}),add:!g};if(!g){j.group.line.reps=[j.group.line.reps.at(-1)||8];delete j.group.line.qual;delete j.group.line.tag;}}
 else if(a==='pf-remove-line'){const g=pfGroups(b.rows[i])[+el.dataset.line];pwUndoPoint(b);b.rows[i].lines=b.rows[i].lines.filter((_,k)=>!g.indices.includes(k));b.source='Your draft';b.target=null;}
 else if(a==='pf-group-cancel')j.group=null;
 else if(a==='pf-group-save'){const g=j.group,w=Number(document.getElementById('pf-weight').value),text=document.getElementById('pf-reps').value.trim(),reps=text.split(/\s+/).map(Number);if(!Number.isFinite(w)||w<0||w>10000||!text||reps.length>100||reps.some(n=>!Number.isInteger(n)||n<1||n>10000))throw Error('Enter a valid weight and positive whole-number reps separated by spaces.');pwUndoPoint(b);const line={...g.line,w,reps};delete line.raw;const lines=Array.from({length:Math.ceil(reps.length/12)},(_,k)=>({...line,reps:reps.slice(k*12,k*12+12)}));if(g.add)b.rows[g.index].lines.push(...lines);else b.rows[g.index].lines.splice(g.indices[0],g.indices.length,...lines);b.source='Your draft';b.target=null;if(!b.locks.includes(g.index))b.locks.push(g.index);j.group=null;}
 else if(a==='pf-save'||a==='pf-confirm-save'){pfSave(a==='pf-confirm-save');return;}
 pwPersist();pwRender();
}
pwHandle=function(e){if(e.target.closest('[data-pw="pf-settings"]')){pfHandle('pf-settings',e.target.closest('[data-pw]'));return true;}if(!pfOn())return pfLegacy.handle(e);const el=e.target.closest('[data-pw]');if(!el)return false;const a=el.dataset.pw,s=pw(),j=pfState();try{if(a.startsWith('pf-')){pfHandle(a,el);return true;}if(a==='date'){const result=pfLegacy.handle(e);j.removed=j.removed.filter(x=>!s.dates.includes(x.date));pwPersist();return result;}if(a==='load-newer'||a==='replace-newer'){const d=s.conflict,result=pfLegacy.handle(e);if(d){if(a==='load-newer')j.removed=j.removed.filter(x=>x.date!==d);else j.removed.forEach(x=>{if(x.date===d)x.base=pwFingerprint(d);});s.step='edit';pwPersist();pwRender();}return result;}if(a==='save'){pfSave();return true;}if(a==='dates-toggle'){pfNavigate('dates');return true;}if(a==='day'){s.active=el.dataset.date;pfNavigate('edit');return true;}if(a==='back'&&['paste','editrow','candidate'].includes(s.step)){s.candidate=null;pfNavigate(pfMatch()?'edit':'dates');return true;}if(a==='edit'){s.candidate=null;pfNavigate(pfMatch()?'edit':'dates');return true;}return pfLegacy.handle(e);}catch(err){s.error=err.message;pwRender();return true;}};
document.addEventListener('input',e=>{if(!pfOn())return;const key=e.target.dataset.pfPref,part=e.target.dataset.pfEmphasis;if(!key&&!part)return;const p=pfState().prefs;if(!p)return;if(part){p.emphasis[part]=+e.target.value;e.target.setAttribute('aria-valuetext',['Less','Balanced','More'][+e.target.value+1]);}else p[key]=key==='split'?e.target.value:+e.target.value;pwPersist();});
document.addEventListener('change',e=>{if(!pfOn())return;if(e.target.matches('[data-pf-paste-all]')){pfState().pasteAll=e.target.checked;pwPersist();return;}if(!e.target.matches('[data-pf-avoid]'))return;const p=pfState().prefs,ex=e.target.value;if(ex&&!p.avoid.includes(ex)){p.avoid.push(ex);pwPersist();pwRender();}});
document.addEventListener('toggle',e=>{if(!pfOn()||!e.target.isConnected||!e.target.matches?.('[data-pf-fold]'))return;const j=pfState();j.open=j.open||{};j.open[e.target.dataset.pfFold]=e.target.open;pwPersist();},true);
(()=>{let drag=null;document.addEventListener('pointerdown',e=>{const g=e.target.closest('[data-pf-day-grip]');if(!g||e.button!==0)return;drag={date:g.dataset.pfDayGrip,owner:pwKey()};g.setPointerCapture?.(e.pointerId);e.preventDefault();});document.addEventListener('pointerup',e=>{if(!drag)return;const from=drag;drag=null;const to=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-pf-day]')?.dataset.pfDay;if(to&&from.owner===pwKey())pfMoveDay(from.date,to);});document.addEventListener('pointercancel',()=>drag=null);document.addEventListener('keydown',e=>{const g=e.target.closest('[data-pf-day-grip]');if(!g||!['ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const ds=pfDates(),i=ds.indexOf(g.dataset.pfDayGrip),d=ds[i+(e.key==='ArrowUp'?-1:1)];if(d){pfMoveDay(g.dataset.pfDayGrip,d);document.querySelector(`[data-pf-day-grip="${d}"]`)?.focus();}});})();
