#!/usr/bin/env python3
"""ios-config.py [DIR] -- apply ShowUp's native settings to the generated ios/ project.

ios/ is generated by `npx cap add ios` and is not committed, so anything set by
hand in Xcode is lost the day it is regenerated. Every native setting ShowUp
depends on is written HERE instead, and `npm run sync:ios` reapplies it after
every sync. Idempotent: run it as often as you like.

Standard library only -- it runs on the Mac, which has python3 through Xcode's
command-line tools and nothing else installed.

What it sets, and why:
  CFBundleURLTypes      the co.yooooooooo.showup:// scheme. Sign-in comes back
                        to the app through it (v4.6.111). Without it iOS has
                        nowhere to deliver the login and it dead-ends in Safari.
  orientations          portrait + both landscapes: landscape is where the big
                        rest timer lives during a live set (v3.3.426).
  iPhone only           TARGETED_DEVICE_FAMILY 1, no iPad, and no "Designed for
                        iPad" builds on Mac or Vision Pro. Shipping iPad means
                        a mandatory iPad screenshot set and an iPad review.
It never touches the bundle identifier: that is chosen per signing account
(.dev on a personal team, the real one under YOOOOOOOOO LLC).
"""
import pathlib, plistlib, re, sys

SCHEME = "co.yooooooooo.showup"          # must equal AUTH_SCHEME in js/core.js
d = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
plist_f = d / "ios/App/App/Info.plist"
pbx_f = d / "ios/App/App.xcodeproj/project.pbxproj"
if not plist_f.exists() or not pbx_f.exists():
    sys.exit("ios-config: no ios/ project here -- run `npx cap add ios` first")

with open(plist_f, "rb") as f:
    pl = plistlib.load(f)
before = plistlib.dumps(pl)
types = [t for t in pl.get("CFBundleURLTypes", []) if SCHEME not in t.get("CFBundleURLSchemes", [])]
types.append({"CFBundleURLName": SCHEME + ".auth", "CFBundleURLSchemes": [SCHEME]})
pl["CFBundleURLTypes"] = types
pl["UISupportedInterfaceOrientations"] = [
    "UIInterfaceOrientationPortrait",
    "UIInterfaceOrientationLandscapeLeft",
    "UIInterfaceOrientationLandscapeRight"]
pl.pop("UISupportedInterfaceOrientations~ipad", None)
if plistlib.dumps(pl) != before:
    with open(plist_f, "wb") as f:
        plistlib.dump(pl, f)

pbx = pbx_f.read_text()
new = re.sub(r'TARGETED_DEVICE_FAMILY = "?[\d,]+"?;', "TARGETED_DEVICE_FAMILY = 1;", pbx)
for key in ("SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD", "SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD", "SUPPORTS_MACCATALYST"):
    new = re.sub(key + r" = \w+;", key + " = NO;", new)
    new = re.sub(r"(\n(\s*)TARGETED_DEVICE_FAMILY = 1;)(?![\s\S]{0,400}?" + key + ")",
                 lambda m: m.group(1) + "\n" + m.group(2) + key + " = NO;", new)
if new != pbx:
    pbx_f.write_text(new)
print(f"ios-config: {SCHEME}:// registered, portrait + landscape, iPhone only")
