#!/usr/bin/env python3
"""ios-config.py [DIR] -- apply ShowUp's native settings to the generated ios/ project.

ios/ is generated by `npx cap add ios` and is not committed, so anything set by
hand in Xcode is lost the day it is regenerated. Every native setting ShowUp
depends on is written HERE instead, and `npm run sync:ios` reapplies it after
every sync. Idempotent: run it as often as you like.

Standard library only -- it runs on the Mac, which has python3 through Xcode's
command-line tools and nothing else installed.

What it sets, and why:
  CFBundleURLTypes      the co.yooooooooo.showup:// scheme. Sign-in comes back
                        to the app through it (v4.6.111). Without it iOS has
                        nowhere to deliver the login and it dead-ends in Safari.
  orientations          portrait + both landscapes: landscape is where the big
                        rest timer lives during a live set (v3.3.426).
  app icon              assets/ios/AppIcon-1024(-dark).png into the asset
                        catalog, replacing Capacitor's placeholder (v4.6.119).
  scroll bounce         Capacitor turns it off; a CAPBridgeViewController
                        subclass turns it back on (v4.6.120).
  Apple Health          write-only HealthKit (v4.6.132): the ShowUpHealth plugin
                        (generated into AppDelegate.swift and registered by the
                        controller), the HealthKit entitlement, and the
                        NSHealthUpdateUsageDescription purpose string. No read
                        permission is ever requested, so no read string exists.
  iPhone only           TARGETED_DEVICE_FAMILY 1, no iPad, and no "Designed for
                        iPad" builds on Mac or Vision Pro. Shipping iPad means
                        a mandatory iPad screenshot set and an iPad review.
It never touches the bundle identifier: that is chosen per signing account
(.dev on a personal team, the real one under YOOOOOOOOO LLC).
"""
import json, pathlib, plistlib, re, shutil, sys

SCHEME = "co.yooooooooo.showup"          # must equal AUTH_SCHEME in js/core.js
HEALTH_WHY = ("ShowUp saves each workout you finish to Apple Health, if you turn this on in Settings: "
              "strength sessions, and runs, rides, rows, swims and walks with their time and distance. "
              "ShowUp never reads your Health data.")
d = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
plist_f = d / "ios/App/App/Info.plist"
pbx_f = d / "ios/App/App.xcodeproj/project.pbxproj"
if not plist_f.exists() or not pbx_f.exists():
    sys.exit("ios-config: no ios/ project here -- run `npx cap add ios` first")

with open(plist_f, "rb") as f:
    pl = plistlib.load(f)
before = plistlib.dumps(pl)
types = [t for t in pl.get("CFBundleURLTypes", []) if SCHEME not in t.get("CFBundleURLSchemes", [])]
types.append({"CFBundleURLName": SCHEME + ".auth", "CFBundleURLSchemes": [SCHEME]})
pl["CFBundleURLTypes"] = types
pl["UISupportedInterfaceOrientations"] = [
    "UIInterfaceOrientationPortrait",
    "UIInterfaceOrientationLandscapeLeft",
    "UIInterfaceOrientationLandscapeRight"]
pl.pop("UISupportedInterfaceOrientations~ipad", None)
# v4.6.132: Apple Health. Specific, because a vague purpose string is its own
# rejection (5.1.1). Write only: ShowUp asks to share workouts, never to read.
pl["NSHealthUpdateUsageDescription"] = HEALTH_WHY
pl.pop("NSHealthShareUsageDescription", None)
if plistlib.dumps(pl) != before:
    with open(plist_f, "wb") as f:
        plistlib.dump(pl, f)

pbx = pbx_f.read_text()
new = re.sub(r'TARGETED_DEVICE_FAMILY = "?[\d,]+"?;', "TARGETED_DEVICE_FAMILY = 1;", pbx)
for key in ("SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD", "SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD", "SUPPORTS_MACCATALYST"):
    new = re.sub(key + r" = \w+;", key + " = NO;", new)
    new = re.sub(r"(\n(\s*)TARGETED_DEVICE_FAMILY = 1;)(?![\s\S]{0,400}?" + key + ")",
                 lambda m: m.group(1) + "\n" + m.group(2) + key + " = NO;", new)
if new != pbx:
    pbx_f.write_text(new)
# v4.6.119: the app icon. assets/ios/ holds the 1024 icons (rendered by
# tools/render-ios-icon.cjs, flattened by tools/ios-icon-finish.py); copy them
# into the asset catalog with an iOS 18 dark variant. Replaces Capacitor's
# placeholder. Byte-compare first so a re-run changes nothing.
icons = d / "assets/ios"
iconset = d / "ios/App/App/Assets.xcassets/AppIcon.appiconset"
if (icons / "AppIcon-1024.png").exists() and iconset.exists():
    for src, dst in (("AppIcon-1024.png", "AppIcon-1024.png"), ("AppIcon-1024-dark.png", "AppIcon-1024-dark.png")):
        s = icons / src
        if s.exists() and (not (iconset / dst).exists() or (iconset / dst).read_bytes() != s.read_bytes()):
            shutil.copyfile(s, iconset / dst)
    images = [{"filename": "AppIcon-1024.png", "idiom": "universal", "platform": "ios", "size": "1024x1024"}]
    if (icons / "AppIcon-1024-dark.png").exists():
        images.append({"appearances": [{"appearance": "luminosity", "value": "dark"}],
                       "filename": "AppIcon-1024-dark.png", "idiom": "universal", "platform": "ios", "size": "1024x1024"})
    contents = json.dumps({"images": images, "info": {"author": "xcode", "version": 1}}, indent=2) + "\n"
    cf = iconset / "Contents.json"
    if not cf.exists() or cf.read_text() != contents:
        cf.write_text(contents)
    old_ph = iconset / "AppIcon-512@2x.png"
    if old_ph.exists():
        old_ph.unlink()                                  # Capacitor's placeholder, now unreferenced
# v4.6.120: the scroll bounce. Capacitor hard-codes scrollView.bounces = false
# when it builds the web view (CAPBridgeViewController.prepareWebView), with no
# config key to undo it, so the app felt rigid at both ends. Its documented
# hook, capacitorDidLoad(), runs after that; a subclass turns the bounce back
# on and the storyboard points at the subclass. The class lives in
# AppDelegate.swift, a file already in the Xcode target, so the project file
# needs no new entry. The web side already keeps the bounce (css/app.css:
# html{overscroll-behavior-y:contain}).
VC_MARK = "// ShowUp: ShowUpViewController (tools/ios-config.py)"
VC_SWIFT = r"""
// ShowUp: ShowUpViewController (tools/ios-config.py)
// Capacitor sets scrollView.bounces = false; ShowUp wants iOS's rubber-band
// at the top and bottom. capacitorDidLoad() runs after Capacitor's setup.
// It also registers ShowUp's own Apple Health plugin (v4.6.132).
class ShowUpViewController: CAPBridgeViewController {
    override func capacitorDidLoad() {
        super.capacitorDidLoad()
        bridge?.registerPluginInstance(ShowUpHealthPlugin())
        enableShowUpBounce()
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        enableShowUpBounce()
    }

    private func enableShowUpBounce() {
        webView?.scrollView.bounces = true
        webView?.scrollView.alwaysBounceVertical = true
        #if DEBUG
        if let scroll = webView?.scrollView {
            print("[ShowUp] Native scroll bounce: enabled=\(scroll.bounces), vertical=\(scroll.alwaysBounceVertical)")
        }
        #endif
    }
}
// End ShowUp: ShowUpViewController
"""
HL_SWIFT = r"""
// ShowUp: ShowUpHealthPlugin (tools/ios-config.py)
// Apple Health, write-only. js/health.js decides what a finished session is;
// this only asks for permission to SHARE workouts and distances, and saves one
// workout per call. It never requests read access and never queries Health.
@objc(ShowUpHealthPlugin)
public class ShowUpHealthPlugin: CAPPlugin, CAPBridgedPlugin {
    public let identifier = "ShowUpHealthPlugin"
    public let jsName = "ShowUpHealth"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "status", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "requestAuthorization", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "saveWorkout", returnType: CAPPluginReturnPromise)
    ]
    private let store = HKHealthStore()

    private var shareTypes: Set<HKSampleType> {
        var types: Set<HKSampleType> = [HKObjectType.workoutType()]
        let ids: [HKQuantityTypeIdentifier] = [.distanceWalkingRunning, .distanceCycling, .distanceSwimming]
        for id in ids {
            if let t = HKObjectType.quantityType(forIdentifier: id) { types.insert(t) }
        }
        return types
    }

    private func currentStatus() -> String {
        guard HKHealthStore.isHealthDataAvailable() else { return "unavailable" }
        switch store.authorizationStatus(for: HKObjectType.workoutType()) {
        case .sharingAuthorized: return "authorized"
        case .sharingDenied: return "denied"
        default: return "notDetermined"
        }
    }

    @objc func status(_ call: CAPPluginCall) {
        call.resolve(["status": currentStatus()])
    }

    @objc func requestAuthorization(_ call: CAPPluginCall) {
        guard HKHealthStore.isHealthDataAvailable() else {
            call.resolve(["status": "unavailable"])
            return
        }
        store.requestAuthorization(toShare: shareTypes, read: nil) { _, error in
            DispatchQueue.main.async {
                if let error = error {
                    call.reject(error.localizedDescription)
                    return
                }
                call.resolve(["status": self.currentStatus()])
            }
        }
    }

    private func activityType(_ name: String) -> HKWorkoutActivityType? {
        switch name {
        case "strength": return .traditionalStrengthTraining
        case "running": return .running
        case "walking": return .walking
        case "cycling": return .cycling
        case "rowing": return .rowing
        case "swimming": return .swimming
        case "elliptical": return .elliptical
        case "stairs": return .stairClimbing
        case "jumprope": return .jumpRope
        default: return nil
        }
    }

    private func distanceType(_ activity: HKWorkoutActivityType) -> HKQuantityType? {
        switch activity {
        case .running, .walking: return HKObjectType.quantityType(forIdentifier: .distanceWalkingRunning)
        case .cycling: return HKObjectType.quantityType(forIdentifier: .distanceCycling)
        case .swimming: return HKObjectType.quantityType(forIdentifier: .distanceSwimming)
        default: return nil
        }
    }

    @objc func saveWorkout(_ call: CAPPluginCall) {
        guard HKHealthStore.isHealthDataAvailable() else {
            call.reject("Apple Health is not available on this device")
            return
        }
        guard let name = call.getString("activity"), let activity = activityType(name),
              let id = call.getString("id"),
              let startMs = call.getDouble("start"), let endMs = call.getDouble("end"), endMs > startMs else {
            call.reject("Invalid workout")
            return
        }
        let start = Date(timeIntervalSince1970: startMs / 1000)
        let end = Date(timeIntervalSince1970: endMs / 1000)
        let meters = call.getDouble("meters") ?? 0
        let configuration = HKWorkoutConfiguration()
        configuration.activityType = activity
        if activity == .swimming { configuration.swimmingLocationType = .unknown }
        let builder = HKWorkoutBuilder(healthStore: store, configuration: configuration, device: .local())
        builder.beginCollection(withStart: start) { began, error in
            guard began else {
                call.reject(error?.localizedDescription ?? "Could not start the workout")
                return
            }
            let finish: () -> Void = {
                builder.endCollection(withEnd: end) { ended, error in
                    guard ended else {
                        call.reject(error?.localizedDescription ?? "Could not end the workout")
                        return
                    }
                    builder.addMetadata([HKMetadataKeyExternalUUID: id]) { _, _ in
                        builder.finishWorkout { workout, error in
                            if let workout = workout {
                                call.resolve(["saved": true, "uuid": workout.uuid.uuidString])
                            } else {
                                call.reject(error?.localizedDescription ?? "Could not save the workout")
                            }
                        }
                    }
                }
            }
            if meters > 0, let type = self.distanceType(activity) {
                let sample = HKQuantitySample(type: type, quantity: HKQuantity(unit: .meter(), doubleValue: meters),
                                              start: start, end: end)
                // A refused distance type still saves the workout itself.
                builder.add([sample]) { _, _ in finish() }
            } else {
                finish()
            }
        }
    }
}
// End ShowUp: ShowUpHealthPlugin
"""
ad = d / "ios/App/App/AppDelegate.swift"
sb = d / "ios/App/App/Base.lproj/Main.storyboard"
if not ad.exists() or not sb.exists():
    sys.exit("ios-config: cannot install bounce: AppDelegate.swift or Main.storyboard is missing")
src = ad.read_text()
s = sb.read_text()
# Match attributes, not their ordering or Xcode's whitespace/quote choices.
# Preserve the rest of the storyboard instead of serializing all its XML.
tags = list(re.finditer(r"<viewController\b[^>]*>", s))
targets = [m for m in tags if re.search(
    r"""\bcustomClass\s*=\s*["'](?:CAPBridgeViewController|ShowUpViewController)["']""", m.group())]
if len(targets) != 1:
    sys.exit("ios-config: expected exactly one Capacitor/ShowUp controller in Main.storyboard; bounce NOT installed")
tag = targets[0]
updated_tag = re.sub(r"""\s+custom(?:Class|Module|ModuleProvider)\s*=\s*["'][^"']*["']""", "", tag.group())
# v4.6.133: keep the tag's own terminator. Capacitor's scene is SELF-CLOSING
# (<viewController .../>); v4.6.120 appended after the slash and wrote
# `.../ customClass=...>`, which ibtool rejects. Stripping the custom* attributes
# first also repairs a tag an earlier run already broke: the stray slash is left
# directly before '>' again.
closing = "/>" if updated_tag.rstrip().endswith("/>") else ">"
updated_tag = updated_tag[:-len(closing)].rstrip() + ' customClass="ShowUpViewController" customModule="App" customModuleProvider="target"' + closing
s2 = s[:tag.start()] + updated_tag + s[tag.end():]

# Replace only our generated class, including the old v4.6.120 block.
# Updating is necessary: a marker is ownership, not proof that code is current.
if VC_MARK in src:
    start = src.index(VC_MARK)
    cls = re.search(r"class ShowUpViewController\s*:\s*CAPBridgeViewController\s*\{", src[start:])
    if not cls:
        sys.exit("ios-config: generated controller marker has no recognized class; refusing to overwrite")
    opening = start + cls.end() - 1
    depth, end = 1, opening + 1
    while end < len(src) and depth:
        depth += (src[end] == "{") - (src[end] == "}")
        end += 1
    if depth:
        sys.exit("ios-config: generated controller is incomplete; refusing to overwrite")
    tail = src[end:]
    tail = re.sub(r"^\s*// End ShowUp: ShowUpViewController[^\n]*", "", tail, count=1)
    src2 = src[:start].rstrip("\n") + "\n" + VC_SWIFT + tail.lstrip("\n")
else:
    if re.search(r"class\s+ShowUpViewController\b", src):
        sys.exit("ios-config: unowned ShowUpViewController exists; refusing to overwrite")
    src2 = src.rstrip("\n") + "\n" + VC_SWIFT
if not re.search(r"^import Capacitor\s*$", src2, re.M):
    sys.exit("ios-config: AppDelegate.swift must import Capacitor")
# v4.6.132: the Apple Health plugin, a generated block of its own between two
# markers, replaced whole on every run. Write-only by construction: the only
# requestAuthorization call passes read: nil.
HL_START = "// ShowUp: ShowUpHealthPlugin (tools/ios-config.py)"
HL_END = "// End ShowUp: ShowUpHealthPlugin"
if HL_START in src2:
    if HL_END not in src2[src2.index(HL_START):]:
        sys.exit("ios-config: generated Health plugin has no end marker; refusing to overwrite")
    a0 = src2.index(HL_START); a1 = src2.index(HL_END, a0) + len(HL_END)
    src2 = src2[:a0].rstrip("\n") + "\n\n" + HL_SWIFT.strip("\n") + "\n" + src2[a1:].lstrip("\n")
else:
    if re.search(r"class\s+ShowUpHealthPlugin\b", src2):
        sys.exit("ios-config: unowned ShowUpHealthPlugin exists; refusing to overwrite")
    src2 = src2.rstrip("\n") + "\n\n" + HL_SWIFT.strip("\n") + "\n"
if not re.search(r"^import HealthKit\s*$", src2, re.M):
    src2 = re.sub(r"^(import Capacitor\s*)$", r"\1\nimport HealthKit", src2, count=1, flags=re.M)
if src2 != src:
    ad.write_text(src2)
if s2 != s:
    sb.write_text(s2)
# v4.6.133: a project whose scene builds its root in code (SceneDelegate.swift,
# rootViewController = CAPBridgeViewController()) never reads the storyboard's
# class, so point that line at the subclass too. Only that exact expression.
scene = d / "ios/App/App/SceneDelegate.swift"
if scene.exists():
    original_scene = scene.read_text()
    configured_scene = re.sub(r"(\brootViewController\s*=\s*)CAPBridgeViewController\s*\(\s*\)",
                              r"\1ShowUpViewController()", original_scene)
    if configured_scene != original_scene:
        scene.write_text(configured_scene)
# v4.6.132: the HealthKit entitlement. If a target already names an
# entitlements file (Xcode writes one the day any capability is added by hand),
# merge into THAT file; otherwise create App/App.entitlements and point every
# App target configuration at it. Keys already there are kept.
ent_rel = None
pbx = pbx_f.read_text()
new = pbx
m = re.search(r'CODE_SIGN_ENTITLEMENTS = "?([^";\n]+)"?;', new)
if m:
    ent_rel = m.group(1).strip()
else:
    ent_rel = "App/App.entitlements"
    new = re.sub(r"(\n(\s*)INFOPLIST_FILE = App/Info\.plist;)",
                 lambda mm: mm.group(1) + "\n" + mm.group(2) + "CODE_SIGN_ENTITLEMENTS = App/App.entitlements;", new)
    if "CODE_SIGN_ENTITLEMENTS" not in new:
        sys.exit("ios-config: found no App target build settings (INFOPLIST_FILE = App/Info.plist); HealthKit NOT installed")
ent_f = d / "ios/App" / ent_rel
ent = {}
if ent_f.exists():
    with open(ent_f, "rb") as f:
        ent = plistlib.load(f)
ent_before = plistlib.dumps(ent)
ent["com.apple.developer.healthkit"] = True
ent.setdefault("com.apple.developer.healthkit.access", [])
if not ent_f.exists() or plistlib.dumps(ent) != ent_before:
    ent_f.parent.mkdir(parents=True, exist_ok=True)
    with open(ent_f, "wb") as f:
        plistlib.dump(ent, f)
if new != pbx:
    pbx_f.write_text(new)
print(f"ios-config: {SCHEME}:// registered, portrait + landscape, iPhone only, ShowUp icon, Apple Health (write-only, {ent_rel})")
print("ios-config: bounce controller installed and storyboard verified. Rebuild/run in Xcode; OTA cannot install native code.")
