// Isolated browser; synthetic profile and sets. No account/network access.
const {chromium,webkit}=require('playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const root=path.resolve(process.argv[2]||'.');
const server=http.createServer((req,res)=>{let f=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(f===root+path.sep)f=path.join(root,'index.html');if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{const data=fs.readFileSync(f);res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.png')?'image/png':'text/html');res.end(data)}catch{res.writeHead(404).end()}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
const browser=process.env.PLATE_BROWSER==='webkit'?await webkit.launch({headless:true}):await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'C:/Users/sungj/AppData/Local/ms-playwright/chromium-1217/chrome-win64/chrome.exe'});
try{const page=await browser.newPage({viewport:{width:393,height:852}});await page.route('**/*',r=>r.request().url().startsWith(origin)?r.continue():r.abort());await page.goto(origin);await page.waitForTimeout(1400);
await page.evaluate(()=>{document.getElementById('onb')?.remove();checkDate=()=>false;DB.settings.name='Profile fixture';DB.settings.sex='f';DB.settings.unit='lb';DB.settings.mascotMotion='animated';DB.days[todayISO]={w:[{ex:'Barbell Bench Press',part:'Chest',w:1433.5/LB,reps:[10],at:Date.now()}]};SEED=deriveAll();view='today';render();});
await page.locator('#nav [data-v="stats"]').click();
await page.waitForSelector('.plate-canvas[data-playing="true"]');
assert(await page.evaluate(()=>platePose(-1,200,1)===null),'Queued plates never draw');
assert(await page.evaluate(()=>platePose(0,200,1).y<0&&platePose(80,200,1).y<platePose(180,200,1).y&&platePose(180,200,1).y<platePose(300,200,1).y),'Fall progresses strictly down from above the canvas');
assert(await page.evaluate(()=>platePose(120,200,1).angle*platePose(120,200,-1).angle<0),'Consecutive plates tilt opposite ways');
assert(await page.locator('.plate-running .su-mascot').count(),'Mascot jumps during build');
assert(await page.locator('.plate-mascot-shadow').count(),'Shadow beneath mascot');
const button=await page.locator('.plate-replay').boundingBox();assert(button.height>=44,'Replay has touch-sized button');
await page.evaluate(()=>document.querySelector('#pmixWrap')?.dispatchEvent(new Event('scroll')));
assert(await page.locator('.plate-canvas').getAttribute('data-playing')==='true','Unrelated chart scrolling leaves playback running');
await page.waitForFunction(()=>{const n=Number(document.querySelector('.plate-total b').textContent.replaceAll(',',''));return n>0&&n<14335});
const partial=await page.locator('.plate-total b').innerText();assert(Number(partial.replaceAll(',',''))%500===0,'Counter advances on full plate landings');
await page.waitForSelector('.plate-canvas[data-playing="false"]');assert(await page.locator('.plate-total b').innerText()==='14,335','Final partial plate lands at exact total');
assert(await page.evaluate(()=>DB.settings.name==='Profile fixture'&&DB.settings.sex==='f'),'Name and gender preserved');
assert(await page.evaluate(()=>Math.abs(plateSeen()-plateCurrent().kg)<.001),'Viewed state persisted');
const centered=await page.evaluate(()=>{const a=document.querySelector('.plate-heading').getBoundingClientRect(),b=document.querySelector('.plate-date').getBoundingClientRect();return Math.abs((a.left+a.right-b.left-b.right)/2)<1;});assert(centered,'Date is centered independently of Share');
await page.evaluate(()=>{window.jumpEvents=0;document.querySelector('.plate-card .su-mascot').addEventListener('mascotreplay',()=>window.jumpEvents++);});
await page.locator('.plate-mascot-button').click();assert(await page.evaluate(()=>window.jumpEvents===1),'Tap replays mascot motion');
assert(await page.evaluate(()=>Math.abs(plateSeen()-plateCurrent().kg)<.001),'Mascot tap does not replay or change ledger');
await page.locator('.plate-share').click();await page.waitForSelector('#repOv');assert(await page.evaluate(()=>_repCv.label==='showup-'+todayISO&&document.querySelector('#repImg').src.startsWith('data:image/png')),'Real workout receipt opens');await page.locator('#repClose').click();
await page.screenshot({path:path.join(root,'../plate-canvas-verified.png')});
await page.locator('.plate-replay').click();await page.waitForSelector('.plate-canvas[data-playing="true"]');
assert(await page.evaluate(()=>Number(document.querySelector('.plate-total b').textContent.replaceAll(',',''))<14335),'Replay resets counter');
await page.locator('#nav [data-v="lift"]').click();await page.waitForFunction(()=>!document.querySelector('.plate-card'));assert(await page.locator('.plate-fall-layer').count()===0,'No overlay left after navigation');
await page.locator('#nav [data-v="stats"]').click();await page.waitForSelector('.plate-canvas[data-playing="false"]');assert(await page.locator('.plate-total b').innerText()==='14,335','Returning keeps saved progress');
await page.evaluate(()=>{DB.days[todayISO].w.push({ex:'Bench',w:500/LB,reps:[1]});renderStats()});await page.waitForSelector('.plate-canvas[data-playing="true"]');assert(await page.evaluate(()=>Number(document.querySelector('.plate-total b').textContent.replaceAll(',',''))>=14335),'Incremental playback starts at seen volume');await page.waitForSelector('.plate-canvas[data-playing="false"]');
await page.evaluate(()=>{DB.days[todayISO].w.pop();renderStats()});await page.waitForSelector('.plate-canvas[data-playing="false"]');assert(await page.locator('.plate-total b').innerText()==='14,335','Deletion recomputes total');
await page.emulateMedia({reducedMotion:'reduce'});await page.locator('.plate-replay').click();await page.waitForTimeout(100);assert(await page.locator('.plate-canvas').getAttribute('data-playing')==='false','Reduced motion suppresses replay and hopping');
await page.evaluate(()=>{document.documentElement.dataset.theme='dark';DB.days[todayISO].doneAll=true;renderStats()});await page.waitForTimeout(100);assert(await page.locator('.plate-card [data-mascot="cool"]').count(),'Completion uses blue mascot');
await page.setViewportSize({width:320,height:740});await page.waitForTimeout(100);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=320),'320px layout fits');
assert(await page.evaluate(()=>plateMetrics({w:[{ex:'Run',w:5,reps:[1]},{ex:'Plank',w:20,reps:[60],su:SET_SEC},{ex:'Squat',w:10,reps:[8,9]},{ex:'Pull Up',w:0,reps:[10]}]}).kg===170),'No fabricated running, hold or bodyweight volume');
assert(await page.evaluate(()=>{const p=plateLedger({w:[{part:'Chest',ex:'Bench',w:650/LB,reps:[1]},{part:'Shoulder',ex:'Press',w:300/LB,reps:[1]}]});return p.length===3&&p[0].part==='Chest'&&p[1].part==='Chest'&&p[2].part==='Shoulder'&&Math.abs(p.at(-1).end*LB-950)<1e-6;}),'Fractional plates preserve body-part totals exactly');
await page.evaluate(()=>{document.documentElement.dataset.theme='light';DB.days[todayISO].w=[{part:'Chest',ex:'Bench',w:800/LB,reps:[10]},{part:'Shoulder',ex:'Press',w:350/LB,reps:[10]},{part:'Triceps',ex:'Extension',w:283.5/LB,reps:[10]}];renderStats()});await page.waitForTimeout(200);
assert(await page.locator('.plate-legend span').count()===3,'Legend names each weighted body part');
assert(await page.evaluate(()=>getComputedStyle(document.querySelectorAll('.plate-legend i')[1]).backgroundColor==='rgb(200, 117, 77)'&&getComputedStyle(document.documentElement).getPropertyValue('--p-shoulder').trim()==='#C8754D'),'Shoulder is shared terracotta, not signature blue');
await page.locator('.plate-card').screenshot({path:path.join(root,'../plate-colors-shipped.png')});
await page.evaluate(()=>{view='lift';lift.ex='Barbell Bench Press';lift.part='Chest';lift.copy=false;renderLift()});assert(await page.locator('.plate-mini').count(),'Training receipt retained');await page.locator('#addrep').click();assert((await page.locator('.plate-mini').innerText()).includes('today'),'Real Add set updates receipt');
console.log('PASS canvas plates: real Stats entry/replay, downward path, alternating tilt, count-up, mascot/shadow, lifecycle, profile, reduced motion and mobile width');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
