// Isolated browser; synthetic profile and sets. No account/network access.
const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const root=path.resolve(process.argv[2]||'.');
const server=http.createServer((req,res)=>{let f=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(f===root+path.sep)f=path.join(root,'index.html');if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{const data=fs.readFileSync(f);res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.png')?'image/png':'text/html');res.end(data)}catch{res.writeHead(404).end()}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'C:/Users/sungj/AppData/Local/ms-playwright/chromium-1217/chrome-win64/chrome.exe'});
try{const page=await browser.newPage({viewport:{width:393,height:852}});await page.route('**/*',r=>r.request().url().startsWith(origin)?r.continue():r.abort());await page.goto(origin);await page.waitForTimeout(1400);
await page.evaluate(()=>{checkDate=()=>false;DB.settings.name='Profile fixture';DB.settings.sex='f';DB.settings.mascotMotion='still';DB.days[todayISO]={w:[{ex:'Barbell Bench Press',part:'Chest',w:135/LB,reps:[10],at:Date.now()}]};SEED=deriveAll();view='stats';renderStats();});
await page.evaluate(()=>document.getElementById('onb')?.remove());
await page.waitForSelector('.plate-fall-layer>svg',{state:'attached'});
assert(await page.locator('.plate-card').count(),'Stats card present');
assert(await page.evaluate(()=>[...document.querySelectorAll('.plate-fall-layer>svg')].every(e=>{const a=e.getAnimations()[0];a.pause();a.currentTime=0;const hiddenOrAbove=getComputedStyle(e).opacity==='0'||e.getBoundingClientRect().bottom<0;a.play();return hiddenOrAbove;})),'Queued plates are hidden and falling plates start above screen');
await page.waitForTimeout(1600);
assert(await page.evaluate(()=>Math.abs(plateSeen()-1350/LB)<.01),'Viewed volume persists');
assert(await page.evaluate(()=>DB.settings.name==='Profile fixture'&&DB.settings.sex==='f'),'Profile preserved');
assert(await page.evaluate(()=>plateMetrics({w:[{ex:'Run',w:5,reps:[1]},{ex:'Plank',w:20,reps:[60],su:SET_SEC},{ex:'Squat',w:10,reps:[8,9]},{ex:'Pull Up',w:0,reps:[10]}]}).kg===170),'No invented running, timed or bodyweight tonnage');
await page.evaluate(()=>{DB.days[todayISO].w.push({ex:'Barbell Bench Press',part:'Chest',w:100/LB,reps:[5]});renderStats()});await page.waitForSelector('.plate-fall-layer>svg',{state:'attached'});
assert(await page.locator('.plate-fall-layer>svg').count()===2,'Only new volume including partial plate animates');
await page.evaluate(()=>{document.querySelector('#view').innerHTML='Other screen'});await page.waitForTimeout(30);assert(await page.locator('.plate-fall-layer').count()===0,'Navigation removes falling overlay');
await page.evaluate(()=>{DB.days[todayISO].w.pop();renderStats()});await page.waitForTimeout(80);assert(await page.locator('.plate-fall-layer').count()===0,'Unchanged viewed total does not rebuild');
await page.locator('.plate-replay').click();await page.waitForSelector('.plate-fall-layer>svg',{state:'attached'});assert(await page.locator('.plate-fall-layer>svg').count()===3,'Replay builds full stack');
await page.evaluate(()=>document.querySelector('#pmixWrap')?.dispatchEvent(new Event('scroll')));
assert(await page.locator('.plate-fall-layer').count()===1,'An unrelated Stats chart scroll must not cancel replay');
await page.waitForTimeout(1400);await page.screenshot({path:path.join(root,'../plate-stats-verified.png')});
await page.evaluate(()=>{localStorage.removeItem(plateKey());view='today';render()});
await page.locator('#nav [data-v="stats"]').click();
await page.waitForSelector('.plate-fall-layer>svg',{state:'attached'});
await page.waitForTimeout(200);
assert(await page.locator('.plate-fall-layer').count()===1,'Real Stats tab entrance survives chart setup and transition');
await page.waitForTimeout(1500);
await page.locator('.plate-replay').click();await page.waitForSelector('.plate-fall-layer>svg',{state:'attached'});
await page.evaluate(()=>document.querySelector('#pmixWrap')?.dispatchEvent(new Event('scroll')));
await page.waitForTimeout(180);
assert(await page.locator('.plate-fall-layer').count()===1,'Replay remains visible on fully initialized Stats page');
await page.waitForTimeout(1500);
await page.locator('.plate-replay').click();await page.waitForSelector('.plate-fall-layer>svg',{state:'attached'});
assert(await page.evaluate(()=>{const copies=[...document.querySelectorAll('.plate-fall-layer>svg')];copies.forEach(e=>{const a=e.getAnimations()[0];a.pause();a.currentTime=0});return copies.slice(1).every(e=>getComputedStyle(e).opacity==='0')}),'Every queued plate is invisible during delay');
assert(await page.locator('.plate-total b').innerText()==='0','Replay starts number at zero');
await page.evaluate(()=>document.querySelector('.plate-fall-layer>svg').getAnimations()[0].finish());await page.waitForTimeout(30);
assert(await page.evaluate(()=>document.querySelector('.plate-total b').textContent===plateNumber(500/LB)),'First landed plate increments number by its volume');
await page.evaluate(()=>document.querySelectorAll('.plate-fall-layer>svg').forEach(e=>e.getAnimations()[0].finish()));await page.waitForTimeout(30);
assert(await page.evaluate(()=>document.querySelector('.plate-total b').textContent===plateNumber(plateCurrent().kg)),'Final partial plate gives exact total');
assert(!(await page.locator('.plate-card').innerText()).includes('1 plate ='),'Scale label removed');
await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>{DB.days[todayISO].w.push({ex:'Squat',part:'Legs',w:100,reps:[10]});renderStats()});await page.waitForTimeout(50);assert(await page.locator('.plate-fall-layer').count()===0,'Reduced motion avoids drop');
await page.evaluate(()=>{document.documentElement.dataset.theme='dark';DB.days[todayISO].doneAll=true;renderStats()});assert(await page.locator('.plate-card [data-mascot="cool"]').count(),'Completed mascot uses blue mode');
await page.setViewportSize({width:320,height:740});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=320),'Compact width has no overflow');
await page.evaluate(()=>{view='lift';lift.ex='Barbell Bench Press';lift.part='Chest';lift.copy=false;renderLift()});assert(await page.locator('.plate-mini').count(),'Training strip rendered');
const before=await page.locator('#addrep').boundingBox();await page.locator('#addrep').click();const after=await page.locator('#addrep').boundingBox();assert(Math.abs(before.height-after.height)<1,'Set button geometry stable');assert((await page.locator('.plate-mini').innerText()).includes('today'),'Training receipt updates');
console.log('PASS plates: viewport entry, incremental/replay, persistence, navigation, units, reduced motion, completion, compact layout, real Add set and profile preservation');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
