// test-pmix.js — v4.4.0: weight-first daily plates and whole-day selection.
const {JSDOM}=require('jsdom'),fs=require('fs'),path=require('path'),vm=require('vm');
const dir=process.argv[2]||'.',html=fs.readFileSync(path.join(dir,'index.html'),'utf8');
const order=[...html.matchAll(/src="(js\/[^?"]+)\?v=/g)].map(m=>m[1]);
const dom=new JSDOM(html.replace(/<script[^>]*src=[^>]*><\/script>/g,''),{url:'https://tahros.github.io/showup/',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,ctx=dom.getInternalVMContext();
w.fetch=()=>Promise.reject(new Error('offline'));w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});w.navigator.vibrate=()=>{};w.scrollTo=()=>{};w.PointerEvent=w.PointerEvent||w.MouseEvent;
w.HTMLCanvasElement.prototype.getContext=function(){return new Proxy({measureText:()=>({width:10})},{get:(o,k)=>k in o?o[k]:()=>({}),set:()=>true});};
for(const s of order)vm.runInContext(fs.readFileSync(path.join(dir,s),'utf8'),ctx,{filename:s});
w.document.dispatchEvent(new w.Event('DOMContentLoaded',{bubbles:true}));
const run=c=>vm.runInContext(c,ctx);let fail=0;
function ok(name,value,detail=''){console.log(value?'PASS':'FAIL',name,detail);if(!value)fail++;}
run(`(function(){DB.days={};const d=new Date(todayISO+'T00:00'),iso=x=>x.toLocaleDateString('en-CA');
 const a=new Date(d);a.setDate(a.getDate()-2);const b=new Date(d);b.setDate(b.getDate()-1);
 DB.settings.unit='lb';DB.days[iso(a)]={w:[{part:'Legs',ex:'Squat',w:100,reps:[8,8,8],at:1}],upd:1};
 DB.days[iso(b)]={w:[{part:'Chest',ex:'Press',w:70,reps:[10,10],at:1},{part:'Back',ex:'Row',w:60,reps:[10],at:2}],upd:1};
 SEED=deriveAll();view='stats';render();})()`);
const titles=()=>run(`[...document.querySelectorAll('#view h2')].map(h=>h.firstChild.textContent.trim())`);
ok('the page leads with the last workout, then accumulation',titles()[0]==='Your work, stacking up'&&titles()[1]==='Your work adds up',titles().slice(0,3).join(' / '));
ok('weight is the default reading',run(`PMIX_MODE==='weight'`));
ok('the alternate sets reading remains available',run(`!!document.querySelector('[data-pmixmode]')&&document.querySelector('[data-pmixmode]').textContent.includes('sets')`));
ok('pounds use whole 500 lb plates',run(`[...document.querySelectorAll('.pmixplate')].every(p=>p.dataset.plateUnit==='500')`));
ok('partial plates preserve non-multiple totals',run(`[...document.querySelectorAll('.pmixplate')].some(p=>+p.getAttribute('height')<5)`));
ok('body-part legend is explanatory, not a filter',run(`document.querySelectorAll('.pmixlgd button').length===0&&document.querySelectorAll('.pmixlgd span').length>=3`));
ok('body-part colors never borrow signature blue',run(`!Object.values(PART_COLORS).includes('var(--accent)')`));
ok('growth, woven, monthly pace, and weight are absent from Stats',!titles().some(t=>/growing|Woven|Monthly pace|^Weight$/i.test(t)));
run(`(function(){const b=document.getElementById('pmixWrap');b.scrollLeft=0;b.getBoundingClientRect=()=>({left:0,top:0,width:340,height:186,right:340,bottom:186});
 const x=8+PMIX_COLW/2;b.dispatchEvent(new PointerEvent('pointerdown',{clientX:x,clientY:50,bubbles:true}));b.dispatchEvent(new PointerEvent('pointerup',{clientX:x,clientY:50,bubbles:true}));})()`);
ok('selecting a column selects the whole day',run(`document.querySelector('.pmixcol.latest')?.dataset.col==='0'`));
ok('the selected day prints one date, weight, and set count',run(`/\\d{4}/.test(document.getElementById('review-day').textContent)&&/lb/.test(document.getElementById('review-day').textContent)&&/sets/.test(document.getElementById('review-day').textContent)`),run(`document.getElementById('review-day').textContent`));
ok('body-part focus stays retired',run(`PMIX_FOCUS===null`));
run(`DB.settings.unit='kg';renderStats();`);
ok('kilograms use whole 250 kg plates',run(`[...document.querySelectorAll('.pmixplate')].every(p=>p.dataset.plateUnit==='250')`));
const story=fs.readFileSync(path.join(dir,'js/stats-story.js'),'utf8');
ok('latest plates keep their rise animation',/\.pmixplate\.latest\{[^}]*animation:pmixrise/.test(story));
ok('latest-column breath and heatmap sheen remain',/pmixlatest/.test(fs.readFileSync(path.join(dir,'css/app.css'),'utf8'))&&/heatframe::after/.test(fs.readFileSync(path.join(dir,'css/app.css'),'utf8')));
ok('pace values use the restrained label scale',/setAttribute\('font-size','6\.5'\)/.test(story)&&/contains\('latest'\)\?'600':'500'/.test(story));
process.exit(fail?1:0);
